## Configfile
configfile: "config/config.yaml"

include: "rules/setup.smk"
include: "rules/common.smk"
include: "rules/intra_inter.smk"
include: "rules/intra_distance.smk"
include: "rules/network.smk"

wildcard_constraints:
    cond="normal|cancer",
    bintype="size|distance|log|onek",
    binsize="\d+"


rule all:
    input:get_output_files

