## Script to get MI boxplots for the different interaction types:
## Inter-Cytoband, Intra-Cytoband, Trans
## per condition.
## It requires the files generated by 3_getNetworkTables
library(data.table)
library(ggplot2)
library(ggthemes)
library(dplyr)

getInterKariobandBoxplot <- function(types){
  
  conds <- c("healthy", "cancer")
  colors <- c("#C7C7C7", "#B37700")
  labels <- c("Healthy", "Cancer")
  names(colors) <- labels
  
  for (type in types){
    cat("Working with type ", type, "\n")
    setwd("/media/ddisk/transpipeline-data/")
    #setwd(paste0("/labs/csbig/regulaciontrans/", type, "/intra"))
    
    mitables <- lapply(X = conds, FUN = function(cond) {
      cat("Reading network ", cond, "\n")
      MIvals <- fread(paste0(type, "/networks/network-tables/", type, "-", cond, "-interactions.tsv"), 
                      header = T, sep="\t", nThread = 3)
      MIvals$cond <- cond
      return(MIvals)
    })
    
    DT <- rbindlist(mitables)
    DT$interaction_type <- factor(DT$interaction_type, levels = c("Intra-Cytoband", "Inter-Cytoband", "Trans"))
    DT$cond <- factor(DT$cond,  levels = conds, labels = labels)
    p <- ggplot(DT) + 
      geom_boxplot(aes(x = interaction_type, y = MI,  fill = interaction_type)) +
      theme_few(base_size = 20) +
      theme(axis.text.x = element_blank(),
            axis.ticks.x = element_blank(),
            strip.text.x = element_text(size = 16),
            axis.title.x = element_blank()) + 
      facet_wrap(~cond, nrow = 1) + 
      ylab("MI") +
      scale_fill_manual(name = "Interaction", values =  c("#1696AC", "#73299e", "#C85200")) 
    
    g <- ggplot_gtable(ggplot_build(p))
    strips <- which(grepl('strip-', g$layout$name))
    for (i in 1:2) {
      k <- which(grepl('rect', g$grobs[[strips[i]]]$grobs[[1]]$childrenOrder))
      g$grobs[[strips[i]]]$grobs[[1]]$children[[k]]$gp$fill <- colors[i]
    }
    
    png(paste0(type, "/figures/mi-boxplot-by-inter-type.png"), width = 1000, height = 500)
    plot(g)
    dev.off()  
  }
}

types <- c("utero")
getInterKariobandBoxplot(types)





