cutoff: 100000
datadir: /datos/ot/diana/regulacion-trans-test
distdir: distance_analysis
figdir: distance_plots
netdir: network
distbin: 100000
sizebin: 1000
algorithm: aracne
tissues: ["livergt", "livertt", "uterusgt", "uterustt"]
biomart: /home/dgarcia/Workspace/distance-analysis/input/Biomart_Ensembl80_GRCh38_p2_regions.tsv
